[theme]
primaryColor = "#FF8A65"
backgroundColor = "#1E1E1E"
secondaryBackgroundColor = "#2D2D2D"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false